### ISSUE TITLE
Tparty

### ISSUE THREAD

**Issue by Wolfenn** [KenshiDRK/Addons#1]
Getting runtime error: Attempt to call string value.
Is this lua meant to replace the code in the tparty windower addon?
Thank you for your help.

**Comment by KenshiDRK** [comment]
Yes, its the same as the normal tparty but adding the distance you are from your pt. Im using right now and I don't have that error. From the error you are getting I think you didn't download the lua with correct formatting, did you copy/pasted it?

**Comment by Wolfenn** [comment]
Yes I copy/pasted from the raw view.

**Comment by KenshiDRK** [comment]
Try doing a right click on the Tparty.lua and save as or you can just download the entire repository

**Comment by Wolfenn** [comment]
That worked, thank you! 
I can see the distances on party members but I can't see the distance to the target. It's not a big issue as I'm using the distance addon, and can just reposition it, but was wondering if you had any ideas.

**Comment by KenshiDRK** [comment]
it doesn't show distance to the target, it is a mistake on the readme. but I might add it if ppl want

**Comment by Wolfenn** [comment]
Oh ok, thank you for clarifying, keep up the good work!
