### ISSUE TITLE
switch icons

### ISSUE THREAD

**Issue by Squeech007** [KenshiDRK/Addons#10]
Suggestion:
Add possibility to use standard icons.
I am having a hard time to get used to the new icons... and yes I know I can switch the png in the icons folder.
Now I couldn't find a source for the original files also I cannot extract them from the dats, because I don't know how to.

Is it possible to easily use the original icons from dats somehow?

Thanks for the awesome and most important addon for any rdm whm brd ^^!!

**Comment by KenshiDRK** [comment]
You can extract the icons with polutils https://github.com/Windower/POLUtils/releases/tag/1.1.6805.10201
but you gotta rename the icons and duplicate someones. I could add an option to switch them but that will make the addon to have so much image files and I'll like to avoid it.

**Comment by Squeech007** [comment]
Thanks alot!
I have managed to find the originals with your XiView entry. 
I only changed the poison and food icons for now, because they confused me the most.

I now appreciate all the work you put into this even more!!

Again: Thanks alot! Also for the quick support!
