### ISSUE TITLE
Debuffing Dancer Steps

### ISSUE THREAD

**Issue by Yamoto07** [KenshiDRK/Addons#11]
Would there be a way to show which Dancer step daze is inflicted? I'm not sure of the procedures to find the spell ID or info like that or I'd try to add it myself. Thanks! :)

**Comment by KenshiDRK** [comment]
I have it almost ready, just thinking if I should use the debuff name or the ability name, thoughs?

**Comment by Yamoto07** [comment]
I think it would depend on how it can be displayed. The debuff has 10(?) levels, whereas the ability is only that. Can a custom entry be used? "Quickstep Lv. 5" instead of "Quickstep" or "Lethargic Daze Lv. 5" for example?

**Comment by KenshiDRK** [comment]
yes both can be used, just dunno what ppl prefer

**Comment by Yamoto07** [comment]
I personally prefer the step name and level as opposed to the daze name, but that's just me.

**Comment by KenshiDRK** [comment]
Added them, closing the issue. Let me know if something is wrong.
