### ISSUE TITLE
Add trust buff/debuff tracking

### ISSUE THREAD

**Issue by RandomCat** [KenshiDRK/Addons#12]
This is more of a feature request than a bug, but how possible would it be to add trust tracking to the PartyBuffs addon? Your TParty mod is able to pull trust TP, though I understand that might be through an entirely different method. I'm hoping trust buffs and debuffs have a similar easy solution. Is it possible?

**Comment by KenshiDRK** [comment]
Thats not possible, the server doesn't send info of the buffs and debuffs the trusts have.
