### ISSUE TITLE
moving partybuffs

### ISSUE THREAD

**Issue by BombSDiggity** [KenshiDRK/Addons#14]
is there a way to move it over to the right? i have tried all the ways i have thought of, but i have been unable to get it to side over. awesome addon though. only had it for about a month but its a real game changer. -thanks in advance

**Comment by KenshiDRK** [comment]
moving it is not implemented as a command, you'll have to modify the lua. On line 127 of partybuffs.lua, modify the 190 to move it, less than 190 to move it to the right. Let me know if you have success.

**Comment by BombSDiggity** [comment]
You da mans boss, thanks!
