### ISSUE TITLE
removing distance

### ISSUE THREAD

**Issue by CLDR1** [KenshiDRK/Addons#15]
is there a way to remove the distance. It is very distracting to me when it keeps changing

**Comment by KenshiDRK** [comment]
Are you talking about the tparty addon? if so there should be a setting in the settings.xml but anyway if you don't want the party distance you could just use the official version.

**Comment by CLDR1** [comment]
Sorry I forgot to mention, I mean the PartyBuffs, I use it when I'm on healing and the distance numbers for each member is very distracting

**Comment by KenshiDRK** [comment]
you are confused, partybuffs doesn't have a distance feature.

**Comment by CLDR1** [comment]
I'm so sorry I confused your addon to the clone one for Ashita.
