### ISSUE TITLE
Original Icons - Unsuccessful attempt

### ISSUE THREAD

**Issue by CLDR1** [KenshiDRK/Addons#16]
I took the original icons posted by RadialArcana here
https://www.ffxiah.com/forum/topic/55168/xivparty-party-list-addon-for-windower-4/4/#3549293
 
Changed them to PNG but now it only shows blank white box for each icon.

I was hoping for a way to use the original icons >.< otherwise LOVE IT!

**Comment by KenshiDRK** [comment]
xivparty is not my addon, or are you speaking of partybuffs?

**Comment by CLDR1** [comment]
Yes partybuffs (btw It made me a better healer thank you!!) your addon is the sole reason why I use windower for my RDM

someone was able to get the original icons and I used them to replace what is in the icons folder

\Windower\addons\PartyBuffs\icons

but they show as a blank white boxes now

Original icons
https://drive.google.com/file/d/1FkGmELfTx-jn5BLrRa1i4WpolvQM5Fl-/view?usp=sharing

**Comment by KenshiDRK** [comment]
the link you posted have the icons as .bmp they need to be .png images

**Comment by CLDR1** [comment]
I switched them all to png using a converter and replaced them. Didn't work unfortunately

**Comment by KenshiDRK** [comment]
make sure they are named correctly, they have to work if you did it ok.

**Comment by CLDR1** [comment]
tried twice but couldn't make it work :(

1) Downloaded
https://drive.google.com/file/d/1FkGmELfTx-jn5BLrRa1i4WpolvQM5Fl-/view?usp=sharing

2) converted them all to png using a public tool

3) replaced the ones in the folder

when I load the addon, all icons show up as a white rectangle

**Comment by KenshiDRK** [comment]
if the path and the name is correct, maybe the converting tool is not converting them right.
