### ISSUE TITLE
Update broke the addon...

### ISSUE THREAD

**Issue by Comgamer7** [KenshiDRK/Addons#18]
Since todays update, it no longer displays anything.

**Comment by KenshiDRK** [comment]
The packet that has the info has changed, it will fix itself when the packet library in windower gets updated, is updated on the dev branch and is being tested before goin live.

**Comment by Comgamer7** [comment]
Sounds good, TY!

**Comment by KenshiDRK** [comment]
Fix is live, relauncher windower to get it.
