### ISSUE TITLE
Cannot adjust x-position

### ISSUE THREAD

**Issue by Shylo-Musgrove** [KenshiDRK/Addons#19]
I just downloaded the current version and not thinking I replaced my settings file. Now, no matter what I do, I am unable to move the buffs to the right. I want them right against the border for the party list but changing the settings file does nothing. I have input 0 all the way up to 1800 and nothing changed.
![PB](https://user-images.githubusercontent.com/11098447/172453674-29f832a2-879a-4d53-bfd1-73edc99ddf76.PNG)

**Comment by KenshiDRK** [comment]
you can't with the settings file, is not mean to be changed really, it is placed that way to account for pt members distance from my tparty version and the lots results from treasure. To modify you have to modify the partybuffs.lua line 62.

**Comment by Shylo-Musgrove** [comment]
> you can't with the settings file, is not mean to be changed really, it is placed that way to account for pt members distance from my tparty version and the lots results from treasure. To modify you have to modify the partybuffs.lua line 62.

Awesome, that worked! For me, I have no need to know the distance of my party members. Might I suggest adding the ability to adjust it for anyone who doesn't want to use that feature? Or at least include in the Read me file how to do it.

Regardless, thanks for this!

**Comment by GBEY0402** [comment]
> you can't with the settings file, is not mean to be changed really, it is placed that way to account for pt members distance from my tparty version and the lots results from treasure. To modify you have to modify the partybuffs.lua line 62.

i put it in the settings.xml very easily
just add <pos_x>130</pos_x> to the settings.xml with the others settings and then replace the number on line 61 by "settings.pos_x" without the ". it will move a few pixels left of the party list.

**Comment by KenshiDRK** [comment]
Added an option to change the x position on last version.
