### ISSUE TITLE
PartyPets - Error message whenever a pet dies/is desummoned/isn't summoned

### ISSUE THREAD

**Issue by yeemuus** [KenshiDRK/Addons#21]
Error message displays as: Lua runtime error: partypets/partypets.lua:160: attempt to index a nil value

Happens with any pet (bst, pup, drg, pup, smn, geo)

**Comment by KenshiDRK** [comment]
Retail or private server?

**Comment by yeemuus** [comment]
Retail

**Comment by yeemuus** [comment]
Sorry that one is probably related to the nameplate addon I just installed or something, the actual error message that I've had since installing partypets is:

PartyPets: Lua runtime error: partypets/partypets.lua:327: table index is nil

**Comment by KenshiDRK** [comment]
I'll check it, when does it happens? I'm not having the issue personally

**Comment by yeemuus** [comment]
When zoning, when changing to a pet job, when a pet dies, when a pet is released, etc.

**Comment by yeemuus** [comment]
You know what, I'm dumb. Just noticed I am using the old Icydeath version. Just installed the one from your repository and it seems to be working fine. Sorry

**Comment by KenshiDRK** [comment]
Good to know, closing the issue.
