### ISSUE TITLE
OmenHelper displays incorrect info

### ISSUE THREAD

**Issue by beerman212** [KenshiDRK/Addons#3]
Since the new omen campaign started OmenHelper has been displaying the incorrect objectives and no omens.  In the case of Cure for 500+ HP 10 times, it shows 1 fewer objective (i.e. 2 instead of 3 on floors 1-2).

Near as I can tell, every single message_id has been incremented by 1.  I went through on my download and added 1 to every id in messages.lua and in omenhelper.lua I did the same anywhere it lists message_ids.  That seems to have fixed it.

I haven't seen anyone else complaining about it, just thought I would point it out.

**Comment by KenshiDRK** [comment]
Thx for pointing it out, I haven't done omen in a long time, I'll check it when I get some free time, dunno if the change will be permanent or just while the campaign is on.

**Comment by beerman212** [comment]
Yeah, I commented all the original values in case it does switch back at the end of the campaign.  Thank you for your work, all of your addons have been very helpful to me.

**Comment by KenshiDRK** [comment]
Updated the messages id, closing the issue.
