### ISSUE TITLE
Pricer doesn't work.

### ISSUE THREAD

**Issue by xxxKaiserxxx** [KenshiDRK/Addons#4]
Hi,

I'm not sure if it's issue with your addon or it's related to ffxiah changing the http to https. (all of the pictures there doesn't show and broken for me like profile avatars, screenshots, etc.)

When I do search for item using this command:
//price wind crystal

I get this error:
Pricer: Lua runtime error: pricer/pricer.lua:95: bad argument #1 to 'gmatch' (string expected, got nil)

**Comment by KenshiDRK** [comment]
Yea, it has to do with the change to https, so now I need a new library that support ssl/tls, as LuaSocket doesn't support it, dunno if I'll be able to fix it and when.

**Comment by xxxKaiserxxx** [comment]
I thought so.
I hope you will be able to fix it when you have time.

Thank you, Kenshi.

**Comment by KenshiDRK** [comment]
So I was able to make luasec work on windower, I have this fixed but I have not updated it cause I'm trying to get the libraries accepted officially on windower, so you only need to replace the pricer lua instead of need to add a few more files.
