### ISSUE TITLE
Infobar addon.

### ISSUE THREAD

**Issue by xxxKaiserxxx** [KenshiDRK/Addons#5]
Hello,

I'm using your Infobar addon (i'm not sure where I got it from but i feel it was here in your repo. and maybe you have removed it?), and i'm getting error spam in my console when i target specific mobs like (Giant Hunter) or (Giant Ranger) in Qufim Island (there is more names if you want).

The error in my console:

Lua runtime error: infobar/infobar.lua:239: attempt to perform arithmetic on  a nil value.

Any idea on how to fix it? or if you have a newer version?

I'm using this version:
_addon.name = 'Infobar'
_addon.author = 'Kenshi'
_addon.version = '1.0'

One last thing..
How to change the player pos x,y,z and replace it with the area/zone name? and how to show the weakness and aggro type when i target the mob because as of now it show only the mob's name.

**Comment by KenshiDRK** [comment]
I sent a pull request to windower some time ago, but it still needs to be accepted, you probably have a version I send you from a pm in the windower forums. Anyway you can try the one here, it should have a readme that explains how to change what to display.

https://github.com/Windower/Lua/pull/1556

**Comment by xxxKaiserxxx** [comment]
I hope it will be accepted soon to let everyone enjoy this great addon <3

Yeah right I remember now haha xD I think i'm getting old /whistle

I'm gonna download it now! Thank you /bow

By the way Kenshi, I think I found a newer database here:
https://iyouffxi.wordpress.com/category/programs/infobar/
http://iyouboushi.com/wp-content/plugins/download-monitor/download.php?id=90

Is it the same db you use in your addon?

I'll try to edit the db file using sqlite3 and see if i can update it if there is a missing mobs.

**Comment by KenshiDRK** [comment]
I think thats the db Im using.
