### ISSUE TITLE
PartyBuffs request

### ISSUE THREAD

**Issue by Sechs** [KenshiDRK/Addons#6]
Not an issue but I was wondering how feasible would it be to add a whitelist/blacklist mode to this addon?
It's really awesome but sometimes you see so many buffs you don't care about for your party members that it becomes less useful as a "first glance" utility.

Not sure if this is even feasible at all, but it would be really awesome!

**Comment by KenshiDRK** [comment]
Should be possible, I'll have to check how to do it when I have time (really busy right now).

**Comment by Sechs** [comment]
Probably by buff ID then?
Blacklist mode, put a list of IDs and those get ignored.
Whitelist mode, put a list of IDs and only those get displayed!

No rush, but it would really make this awesome addon even more awesome, if you ask me ^^
Talking form the point of view of buffing jobs, for instance.
Being able to see with a quick glance (instead of looking through the complete list) if your buffs are up or not on a certain target would add tons to the quality of life.

**Comment by KenshiDRK** [comment]
The main problem is I can't test this easy as I don't have 2 accounts, so getting help from someone on ragnarok would help.

**Comment by Sechs** [comment]
Wish I were on Ragnarok to help ya, but alas I'm on good ol' Asura ^^'

**Comment by Sechs** [comment]
Hi Kenshi! Sorry for being the annoying guy who keeps being unsolicitely demanding, but ever gave a serious thought about that whitelist/blacklist mode for Partybuffs? Would *really* change my life, and I bet a lot of supporters' lives!

**Comment by KenshiDRK** [comment]
I'll try to work on it soon, been very busy.

**Comment by aukon** [comment]
I actually updated this recently, just waiting on a fix for RE and it should be available via the Windower launcher.

Can grab it from [here](https://github.com/aukon/Windower-Addons/tree/master/Debuffed) but you'll need to stick the spells.lua in your resources for it to work, for now. It's got blacklist/whitelist functionality.

**Comment by Sechs** [comment]
Man what a big news to begin the day! I WANT TO BE THE MOTHER OF YOUR CHILDREN, AUKON! <3 <3 <3
Will patiently wait for the Windower version to be pulled in the live branch <3

**Comment by KenshiDRK** [comment]
This is a different addon, this one show the buffs of your party members, the one you are talking about is mob debuffs.

**Comment by Sechs** [comment]
I take back my previous "gonna bear your children" statement, Aukon! ;-P

**Comment by KenshiDRK** [comment]
I have the whitelist - blacklist option completed, just need to test it, Sech do you have discord so I can give you the lua for test?

**Comment by Sechs** [comment]
Yes! Can find me on Discord with Sechs#7108 or you can upload the lua on pastebin or any other mean and then give me the link here.
I'll be more than glad to do as thorough of a test as I can with BRD and RDM :)
