### ISSUE TITLE
Debuffed not tracking some debuffs

### ISSUE THREAD

**Issue by Sechs** [KenshiDRK/Addons#7]
For instance it's not tracking "Addle II" and "Pining Nocturne".
The buff ID of these debuffs are included into the lua, I personally checked, but maybe it's a wrong number because it never displays Nocturne or Addle up.

Also are the timers from this addon are the "default" ones, right? (without any duration increase calculations from Merits, Job Points, Gifts and gear?)

**Comment by KenshiDRK** [comment]
the number is not the buff id is the spell id, I'll have to check it, I can test the nocturne one but as my rdm doesn't have the lvl for addle II I can't test it.
The timers doesn't take them into account, I wanted to make it possible to set the duration manually as taking into account all of the gear and merits, jp its a lot of work (and this only will work for spells you cast), but due to being unable to know if a mob partially resisted a spell the duration won't be accurate sometimes.

**Comment by Sechs** [comment]
Yeah, I tried to build such an addon myself long ago but it's impossible given the lack of info from the packets.
Also this addon currently tracks (through battle chat packets) the debuffs cast from other players as well, which has pros and cons but normally it's a really nice feature I'd say, especially on long/single target fights.

**Comment by KenshiDRK** [comment]
I'll update it in a min with a fix for pining nocturne and hopefully addle as well if they still use same effect sent from packets, looks like SE changed the effect packets send for those spells on some update.

**Comment by KenshiDRK** [comment]
pushed the fix, if you can check if addle works will be awesome, I also added support for showing the debuffs of the subtarget when you have a subtarget.

**Comment by Sechs** [comment]
Working for Pining Nocturne, not working for either Addle or Addle II

**Comment by KenshiDRK** [comment]
I checked addle with trust and it was correct before I updated, did addle was working and only addle II was not working? is there a mob that cast addle II so I can test?
Also if you can test how they overwritte between them would be awesome.

**Comment by Sechs** [comment]
I'll try again, but when I swapped to BRD and cast Pining Nocturne on a Mandy outside of adoulin it immediately displayed in Debuffed.
Then I went back as RDM and neither Addle nor Addle II showed on Debuffed /shrugs

Don't think Pining Nocturne can overwrite Addle or Addle II, or at least it couldn't before they raised its potency some patches ago, things might be different now.

I'll try again tomorrow, going out now and got no time sorry ><


Edit:
to make sure, version 1.2 is the one I'm supposed to be using, correct?

**Comment by Sechs** [comment]
Tried with 1.2, added screenshot this time. Same behaviour as last time.
Most Debuffs appear in the list, but Addle1 and Addle2 get ignored even though they stick.

Maybe the Trust version is somehow different from the Player version? Or maybe you're using a more advanced version of Debuffed than my 1.2 /shrugs

https://s10.postimg.org/4sxchcnyh/pol_2018-02-04_20-40-35-90.png

**Comment by KenshiDRK** [comment]
I'm using a different one with addle fixed but not for addle II as I don't have it. If you know about a mob that uses addle II I could check it.

**Comment by Sechs** [comment]
Checked with other people as well. As far as we know there is no monster that casts Addle II in game atm.
If you want to pass unto me your temporary lua though I can test it in your place with my RDM :)

**Comment by KenshiDRK** [comment]
https://gist.github.com/KenshiDRK/c9da8e95ff46baf4a5071326a67f56f8

Try this, this one should print a number to the console after casting, cast addle 2 and tell me what number it prints. Also, test addle, this one should work for addle.

**Comment by Sechs** [comment]
It prints "21" on both Addle and Addle II and it seems to be tracking both. Can't tell for the durations of course, but as far as the tracking goes it seems to be working! /highfive man

**Comment by KenshiDRK** [comment]
cool, I'll update it on repository when I get time.
