### ISSUE TITLE
TParty: what are these numbers exactely?

### ISSUE THREAD

**Issue by Sechs** [KenshiDRK/Addons#8]
See the screenshot. I get the third number in the lower right is somehow related to the Z axis, but what are the other two numbers?

https://s10.postimg.org/lbah8zfm1/tparty.jpg

**Comment by KenshiDRK** [comment]
the lower right is the distance between you and your target in the z axis (height), the upper right is the 2d distance that normal tparty shows, the bigger left is the 3d distance taking into account the 3 axis (x,y,z)
