### ISSUE TITLE
debuffed: missing debuffs

### ISSUE THREAD

**Issue by deadman80** [KenshiDRK/Addons#9]
The -ja line of elemental AOE BLM nukes (ie: Firaja, Blizzaja, etc. plus Comet) actually applies a stacking debuff with a 60sec duration that is only modified by empyrean armor, and caps at 5x stacks from all casters during the duration. 

https://www.bg-wiki.com/bg/Category:Cumulative_Magic

Is there any way to add the debuff to the addon, hopefully with tracking stacks (and ideally, tracking stacks from multiple casters)?

**Comment by KenshiDRK** [comment]
This is a little difficult to implement as everything needs to be hardcoded, I'll take a look on it when I have some time.

**Comment by KenshiDRK** [comment]
Updated Debuffed, it doesn't take into account equipment for several reasons, it could be possible to track your equipment but its not possible for others. If you use empyrean armor change the 60 on line 188 to whatever you need. Also changed the addon name to Debuffing so it doesn't conflict with the official windower addon. Feel free to post here or create a new issue if you find a bug.
